"""add quiz_data to parts

Revision ID: 1483bd9236fc
Revises: 6655181ac031
Create Date: 2026-03-25 19:22:11.164474
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1483bd9236fc'
down_revision: Union[str, None] = '6655181ac031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('quiz_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'quiz_data')
    # ### end Alembic commands ###
